import fs from "node:fs/promises"
import path from "node:path"

const root = path.resolve(import.meta.dirname, "../examples")
const output = path.join(root, "__index__.tsx")

const TARGET_EXTENSIONS = {
  react: new Set([".tsx", ".jsx"]),
  html: new Set([".html"]),
} as const

type Target = keyof typeof TARGET_EXTENSIONS

type ImportEntry = {
  name: string
  path: string
}

type ReactExamples = Record<string, string>
type HtmlExamples = Record<string, string>

type ExamplesIndex = Record<
  string,
  {
    react?: ReactExamples
    html?: HtmlExamples
  }
>

async function getDirectories(directory: string) {
  const entries = await fs.readdir(directory, {
    withFileTypes: true,
  })

  return entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort()
}

async function getFiles(directory: string, target: Target) {
  const extensions = TARGET_EXTENSIONS[target]

  const entries = await fs.readdir(directory, {
    withFileTypes: true,
  })

  return entries
    .filter(
      (entry) =>
        entry.isFile() && extensions.has(path.extname(entry.name).toLowerCase())
    )
    .map((entry) => entry.name)
    .sort()
}

function toPascalCase(value: string) {
  return value
    .replace(/[-_]+(.)?/g, (_, char: string | undefined) =>
      char ? char.toUpperCase() : ""
    )
    .replace(/^(.)/, (_, char: string) => char.toUpperCase())
}

function toImportName(name: string, index: number) {
  const identifier = toPascalCase(name)

  return identifier || `Example${index}`
}

async function build() {
  const imports: ImportEntry[] = []
  const examples: ExamplesIndex = {}

  const styles = await getDirectories(root)

  console.log()
  console.log("📋 Building examples/__index__.tsx")
  console.log()

  for (const style of styles) {
    if (style.startsWith("_") || style.startsWith(".")) {
      continue
    }

    const stylePath = path.join(root, style)
    const targets = await getDirectories(stylePath)

    let styleExampleCount = 0

    console.log(`  ${style}`)

    examples[style] ??= {}

    for (const target of targets) {
      if (target !== "react" && target !== "html") {
        continue
      }

      const targetPath = path.join(stylePath, target)
      const files = await getFiles(targetPath, target)

      if (files.length === 0) {
        continue
      }

      if (target === "react") {
        examples[style].react ??= {}

        console.log(`  ├─ ${target}`)

        for (let index = 0; index < files.length; index++) {
          const file = files[index]
          const isLast = index === files.length - 1

          const name = path.basename(file, path.extname(file))

          const importName = toImportName(
            `${style}-${target}-${name}`,
            imports.length
          )

          const importPath = `./${style}/${target}/${name}`

          imports.push({
            name: importName,
            path: importPath,
          })

          examples[style].react[name] = importName

          styleExampleCount++

          const branch = isLast ? "└─" : "├─"

          console.log(`  │  ${branch} ✓ ${file}`)
        }
      }

      if (target === "html") {
        examples[style].html ??= {}

        console.log(`  ├─ ${target}`)

        for (let index = 0; index < files.length; index++) {
          const file = files[index]
          const isLast = index === files.length - 1

          const name = path.basename(file, path.extname(file))

          // Path relative to the examples directory.
          const examplePath = `${style}/${target}/${file}`

          examples[style].html[name] = examplePath

          styleExampleCount++

          const branch = isLast ? "└─" : "├─"

          console.log(`  │  ${branch} ✓ ${file}`)
        }
      }
    }

    if (styleExampleCount === 0) {
      console.log(`  └─ no examples`)
    }

    console.log()
  }

  const lines: string[] = []

  lines.push("/* eslint-disable @typescript-eslint/no-explicit-any */")
  lines.push("// This file is autogenerated by scripts/build-examples.mts")
  lines.push("// Do not edit this file directly.")
  lines.push("")
  lines.push('import "server-only"')
  lines.push("")

  for (const item of imports) {
    lines.push(`import ${item.name} from "${item.path}"`)
  }

  lines.push("")

  lines.push(
    "export const ExamplesIndex: Record<string, Record<string, Record<string, any>>> = {"
  )

  for (const [style, targets] of Object.entries(examples)) {
    lines.push(`  ${JSON.stringify(style)}: {`)

    if (targets.react) {
      lines.push(`    "react": {`)

      for (const [name, importName] of Object.entries(targets.react)) {
        lines.push(`      ${JSON.stringify(name)}: ${importName},`)
      }

      lines.push("    },")
    }

    if (targets.html) {
      lines.push(`    "html": {`)

      for (const [name, examplePath] of Object.entries(targets.html)) {
        lines.push(
          `      ${JSON.stringify(name)}: ${JSON.stringify(examplePath)},`
        )
      }

      lines.push("    },")
    }

    lines.push("  },")
  }

  lines.push("}")
  lines.push("")

  await fs.writeFile(output, lines.join("\n"), "utf8")

  console.log(`✓ Generated: ${path.relative(process.cwd(), output)}`)

  console.log(
    `✓ ${imports.length} React example${
      imports.length === 1 ? "" : "s"
    } registered`
  )

  console.log("✓ HTML examples are registered as source paths.")
}

build().catch((error) => {
  console.error()
  console.error("✗ Failed to build examples")
  console.error()
  console.error(error)
  process.exit(1)
})
