// scripts/build-examples.mts

import fs from "node:fs/promises"
import path from "node:path"

const root = path.resolve(import.meta.dirname, "../examples")
const output = path.join(root, "__index__.tsx")

const SOURCE_EXTENSIONS = new Set([".tsx", ".jsx"])

type ImportEntry = {
  name: string
  path: string
}

type ExamplesIndex = Record<string, Record<string, Record<string, string>>>

async function getDirectories(directory: string) {
  const entries = await fs.readdir(directory, {
    withFileTypes: true,
  })

  return entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort()
}

async function getFiles(directory: string) {
  const entries = await fs.readdir(directory, {
    withFileTypes: true,
  })

  return entries
    .filter(
      (entry) =>
        entry.isFile() && SOURCE_EXTENSIONS.has(path.extname(entry.name))
    )
    .map((entry) => entry.name)
    .sort()
}

function toPascalCase(value: string) {
  return value
    .replace(/[-_]+(.)?/g, (_, char: string | undefined) =>
      char ? char.toUpperCase() : ""
    )
    .replace(/^(.)/, (_, char: string) => char.toUpperCase())
}

function toImportName(name: string, index: number) {
  const identifier = toPascalCase(name)

  return identifier || `Example${index}`
}

async function build() {
  const imports: ImportEntry[] = []
  const examples: ExamplesIndex = {}

  const styles = await getDirectories(root)

  console.log()
  console.log("📋 Building examples/__index__.tsx")
  console.log()

  for (const style of styles) {
    if (style.startsWith("_") || style.startsWith(".")) {
      continue
    }

    const stylePath = path.join(root, style)
    const targets = await getDirectories(stylePath)

    let styleExampleCount = 0

    console.log(`  ${style}`)

    examples[style] ??= {}

    for (const target of targets) {
      const targetPath = path.join(stylePath, target)
      const files = await getFiles(targetPath)

      if (files.length === 0) {
        continue
      }

      examples[style][target] ??= {}

      console.log(`  ├─ ${target}`)

      for (let index = 0; index < files.length; index++) {
        const file = files[index]
        const isLast = index === files.length - 1

        const name = path.basename(file, path.extname(file))

        const importName = toImportName(
          `${style}-${target}-${name}`,
          imports.length
        )

        const importPath = `./${style}/${target}/${name}`

        imports.push({
          name: importName,
          path: importPath,
        })

        examples[style][target][name] = importName

        styleExampleCount++

        const branch = isLast ? "└─" : "├─"

        console.log(`  │  ${branch} ` + "✓" + " " + file)
      }
    }

    if (styleExampleCount === 0) {
      console.log(`  └─ no examples`)
    }

    console.log()
  }

  const lines: string[] = []

  lines.push("/* eslint-disable @typescript-eslint/no-explicit-any */")
  lines.push("// This file is autogenerated by scripts/build-examples.mts")
  lines.push("// Do not edit this file directly.")
  lines.push("")
  lines.push('import "server-only"')
  lines.push("")

  for (const item of imports) {
    lines.push(`import ${item.name} from "${item.path}"`)
  }

  lines.push("")
  lines.push(
    "export const ExamplesIndex: Record<string, Record<string, any>> = {"
  )

  for (const [style, targets] of Object.entries(examples)) {
    lines.push(`  ${JSON.stringify(style)}: {`)

    for (const [target, demoExamples] of Object.entries(targets)) {
      lines.push(`    ${JSON.stringify(target)}: {`)

      for (const [name, importName] of Object.entries(demoExamples)) {
        lines.push(`      ${JSON.stringify(name)}: ${importName},`)
      }

      lines.push("    },")
    }

    lines.push("  },")
  }

  lines.push("}")
  lines.push("")

  await fs.writeFile(output, lines.join("\n"), "utf8")

  console.log("✓" + " " + `Generated: ${path.relative(process.cwd(), output)}`)

  console.log(
    "✓" +
      " " +
      `${imports.length} example${imports.length === 1 ? "" : "s"} registered`
  )

  console.log()
}

build().catch((error) => {
  console.error()
  console.error("✗ Failed to build examples")
  console.error()
  console.error(error)
  process.exit(1)
})
