import { COLOR_NAMES } from "@/lib/colors/palette"
import { mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, resolve, relative } from "node:path"

const COLORS = [
  "red",
  "orange",
  "amber",
  "yellow",
  "lime",
  "green",
  "emerald",
  "teal",
  "cyan",
  "sky",
  "blue",
  "indigo",
  "violet",
  "purple",
  "fuchsia",
  "pink",
  "rose",
  "slate",
  "gray",
  "zinc",
  "neutral",
  "stone",
  "mauve",
  "olive",
  "mist",
  "taupe",
] as const

const SHADES = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950] as const

const inputPath = resolve(process.argv[2] ?? "themes.css")
const outputPath = resolve(process.argv[3] ?? "lib/colors/palette.ts")

const css = readFileSync(inputPath, "utf8")

const found = new Map<string, string>()
for (const match of css.matchAll(/--np-([a-z]+)-(\d+):\s*([^;]+);/g)) {
  found.set(`${match[1]}-${match[2]}`, match[3].trim())
}

const missing: string[] = []
let body = ""
for (const color of COLORS) {
  body += `  ${color}: {\n`
  for (const shade of SHADES) {
    const value = found.get(`${color}-${shade}`)
    if (!value) {
      missing.push(`--np-${color}-${shade}`)
      continue
    }
    body += `    ${shade}: ${JSON.stringify(value)},\n`
  }
  body += "  },\n"
}

if (missing.length > 0) {
  console.error(
    `\nMissing ${missing.length} variable(s) in ${relative(process.cwd(), inputPath)}:`
  )
  for (const name of missing.slice(0, 10)) console.error(`  ${name}`)
  if (missing.length > 10) console.error(` ...and ${missing.length - 10} more`)
  process.exit(1)
}

const output = `//* This file is autogenerated by scripts/generate-palette.mts
//! Do not edit this file directly.

export const COLOR_NAMES = ${JSON.stringify(COLORS)} as const;
export const SHADES = ${JSON.stringify(SHADES)} as const;

export type ColorName = (typeof COLOR_NAMES)[number];
export type Shade = (typeof SHADES)[number];

export const PALETTE: Record<ColorName, Record<Shade, string>> = {
${body}};

export const SPECIALS = {
  black: "oklch(0 0 0)",
  white: "oklch(1 0 0)",
} as const;

export type SpecialName = keyof typeof SPECIALS;
`

mkdirSync(dirname(outputPath), { recursive: true })
writeFileSync(outputPath, output)
console.log(
  `\n✓ Generated ${relative(process.cwd(), outputPath)} from ${relative(process.cwd(), inputPath)}`
)
console.log(
  `✓ ${COLOR_NAMES.length} colors, ${SHADES.length} shades, ${COLOR_NAMES.length * SHADES.length} total variables`
)
