/* eslint-disable @typescript-eslint/no-explicit-any */
// This file is autogenerated by scripts/build-examples.mts
// Do not edit this file directly.

import "server-only"

import KtmReactButtonDefault from "./ktm/react/button-default"
import KtmReactButtonDemo from "./ktm/react/button-demo"
import KtmReactButtonDestructive from "./ktm/react/button-destructive"
import KtmReactButtonDisabled from "./ktm/react/button-disabled"
import KtmReactButtonGhost from "./ktm/react/button-ghost"
import KtmReactButtonIcon from "./ktm/react/button-icon"
import KtmReactButtonLink from "./ktm/react/button-link"
import KtmReactButtonOutline from "./ktm/react/button-outline"
import KtmReactButtonRounded from "./ktm/react/button-rounded"
import KtmReactButtonSecondary from "./ktm/react/button-secondary"
import KtmReactButtonSize from "./ktm/react/button-size"
import KtmReactButtonSpinner from "./ktm/react/button-spinner"
import KtmReactButtonWithIcon from "./ktm/react/button-with-icon"
import KtmReactSpinnerColor from "./ktm/react/spinner-color"
import KtmReactSpinnerDemo from "./ktm/react/spinner-demo"
import KtmReactSpinnerDirection from "./ktm/react/spinner-direction"
import KtmReactSpinnerSize from "./ktm/react/spinner-size"
import KtmReactSpinnerSpeed from "./ktm/react/spinner-speed"
import KtmReactSpinnerThickness from "./ktm/react/spinner-thickness"

export const ExamplesIndex: Record<string, Record<string, any>> = {
  ktm: {
    react: {
      "button-default": KtmReactButtonDefault,
      "button-demo": KtmReactButtonDemo,
      "button-destructive": KtmReactButtonDestructive,
      "button-disabled": KtmReactButtonDisabled,
      "button-ghost": KtmReactButtonGhost,
      "button-icon": KtmReactButtonIcon,
      "button-link": KtmReactButtonLink,
      "button-outline": KtmReactButtonOutline,
      "button-rounded": KtmReactButtonRounded,
      "button-secondary": KtmReactButtonSecondary,
      "button-size": KtmReactButtonSize,
      "button-spinner": KtmReactButtonSpinner,
      "button-with-icon": KtmReactButtonWithIcon,
      "spinner-color": KtmReactSpinnerColor,
      "spinner-demo": KtmReactSpinnerDemo,
      "spinner-direction": KtmReactSpinnerDirection,
      "spinner-size": KtmReactSpinnerSize,
      "spinner-speed": KtmReactSpinnerSpeed,
      "spinner-thickness": KtmReactSpinnerThickness,
    },
  },
}
