/* eslint-disable @typescript-eslint/no-explicit-any */
// This file is autogenerated by scripts/build-examples.mts
// Do not edit this file directly.

import "server-only"

import KtmReactButtonDefault from "./ktm/react/button-default"
import KtmReactButtonDemo from "./ktm/react/button-demo"
import KtmReactButtonDestructive from "./ktm/react/button-destructive"
import KtmReactButtonGhost from "./ktm/react/button-ghost"
import KtmReactButtonLink from "./ktm/react/button-link"
import KtmReactButtonOutline from "./ktm/react/button-outline"
import KtmReactButtonSecondary from "./ktm/react/button-secondary"
import KtmReactButtonSize from "./ktm/react/button-size"

export const ExamplesIndex: Record<string, Record<string, any>> = {
  ktm: {
    react: {
      "button-default": KtmReactButtonDefault,
      "button-demo": KtmReactButtonDemo,
      "button-destructive": KtmReactButtonDestructive,
      "button-ghost": KtmReactButtonGhost,
      "button-link": KtmReactButtonLink,
      "button-outline": KtmReactButtonOutline,
      "button-secondary": KtmReactButtonSecondary,
      "button-size": KtmReactButtonSize,
    },
  },
}
